### PR TITLE
Sql like explanation for belongs_to has_many

### PR DESCRIPTION
**Pull request by aturkewi**
Changes readme to explain the belongs_to has_many in a way that better maps to SQL. Artist will no longer have `@songs` array, but rather search `Song.all` for songs where they are the artist. 

@pletcher and @JeffKatzy this is my first pass at updating the readme. I'm going to continue by working on the rest of this section, but I was just wondering if I might get a first pass glance over from you to make sure we're on the same page. 

cc: @AnnJohn @PeterBell 

Note: This is not to be merged in until entire section is complete!

### CODE REVIEW

**Comment by pletcher** [comment]
This seems to be on the right track to me. The one thing I notice is that, as a reader/student, I have a really hard time keeping the mapping straight when reading about Songs/Artists, but it's a lot easier seeing the code. So copious code examples would be 👍 

Just a 💭

**Comment by aturkewi** [comment]
cc @mendelB

**Comment by pletcher** [comment]
@aturkewi this looks great!

**Comment by pletcher** [comment]
@aturkewi is this ready to merge?

**Comment by mendelB** [comment]
@pletcher I think the idea was to wait for the go ahead on this, and then do custruction on the later relevant labs to align them with this approach, and once all green to merge 'em all in one go

**Comment by aturkewi** [comment]
@mendelB updated per your comments

**Comment by AnnJohn** [comment]
@aturkewi @mendelB can this be merged?

**Comment by maxwellbenton** [comment]
Hey @aturkewi,

I know it has been a little while since you opened this PR, but I just wanted to follow up with you - I've updated this lesson to include a section that introduces the more SQL-like single source of truth OO structure at the end of this lesson (selecting from the 'belongs-to' side of the relationship rather than maintaining a relationship on both sides with instance variables). We're in the process of updating mod 1 content at the moment, and I working on making this the standard for this section in other lessons as well.

With these fixes, this PR should no longer be needed so I am going to close this now.

Thank you for your contribution! Hope you are well!

**Pull request closed without merging**
